-- Álbum premium de fotos/vídeos por utilizador (máx. 10 itens por usuário via frontend)
-- Execute no SQL Editor do Supabase

CREATE TABLE IF NOT EXISTS public.user_album_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  media_url TEXT NOT NULL,
  media_type TEXT NOT NULL DEFAULT 'image' CHECK (media_type IN ('image', 'video')),
  caption TEXT,
  accent_color TEXT,
  sort_order INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_album_items_user_created
  ON public.user_album_items (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_album_items_user_sort
  ON public.user_album_items (user_id, sort_order ASC);

ALTER TABLE public.user_album_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_album_items_select_all" ON public.user_album_items;
CREATE POLICY "user_album_items_select_all"
  ON public.user_album_items
  FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "user_album_items_insert_own" ON public.user_album_items;
CREATE POLICY "user_album_items_insert_own"
  ON public.user_album_items
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "user_album_items_update_own" ON public.user_album_items;
CREATE POLICY "user_album_items_update_own"
  ON public.user_album_items
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "user_album_items_delete_own" ON public.user_album_items;
CREATE POLICY "user_album_items_delete_own"
  ON public.user_album_items
  FOR DELETE
  USING (auth.uid() = user_id);

DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.user_album_items;
  EXCEPTION
    WHEN duplicate_object THEN NULL;
    WHEN undefined_object THEN NULL;
  END;
END $$;
