-- Create ads table
CREATE TABLE IF NOT EXISTS public.ads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    image_url TEXT NOT NULL,
    link_url TEXT,
    location TEXT,
    phone TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.ads ENABLE ROW LEVEL SECURITY;

-- Drop existing policies
DROP POLICY IF EXISTS "Everyone can view ads" ON public.ads;
DROP POLICY IF EXISTS "Admins can manage ads" ON public.ads;

-- Create policies
CREATE POLICY "Everyone can view ads" 
ON public.ads FOR SELECT 
USING (true);

CREATE POLICY "Admins can manage ads" 
ON public.ads FOR ALL 
USING (
  auth.uid() IN (
    SELECT id FROM public.profiles WHERE role = 'admin'
  ) OR (
    (auth.jwt() ->> 'email') = 'rafaaprodrigu3s@gmail.com'
  )
);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.ads;
