-- 1. Create post_reactions table
CREATE TABLE IF NOT EXISTS public.post_reactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES public.posts(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    reaction_type TEXT NOT NULL DEFAULT 'like',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(post_id, user_id)
);

-- 2. Enable RLS
ALTER TABLE public.post_reactions ENABLE ROW LEVEL SECURITY;

-- 3. Create policies
DROP POLICY IF EXISTS "Anyone can view reactions" ON public.post_reactions;
DROP POLICY IF EXISTS "Users can create their own reactions" ON public.post_reactions;
DROP POLICY IF EXISTS "Users can update their own reactions" ON public.post_reactions;
DROP POLICY IF EXISTS "Users can delete their own reactions" ON public.post_reactions;

CREATE POLICY "Anyone can view reactions" ON public.post_reactions FOR SELECT USING (true);
CREATE POLICY "Users can create their own reactions" ON public.post_reactions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own reactions" ON public.post_reactions FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own reactions" ON public.post_reactions FOR DELETE USING (auth.uid() = user_id);

-- 4. Create RPC functions to safely update reactions (bypasses RLS on posts table)
CREATE OR REPLACE FUNCTION add_post_reaction(p_post_id BIGINT, p_user_id UUID, p_reaction_type TEXT)
RETURNS void AS $$
DECLARE
    v_existing_reaction TEXT;
BEGIN
    SELECT reaction_type INTO v_existing_reaction FROM public.post_reactions WHERE post_id = p_post_id AND user_id = p_user_id;
    
    IF v_existing_reaction IS NULL THEN
        INSERT INTO public.post_reactions (post_id, user_id, reaction_type) VALUES (p_post_id, p_user_id, p_reaction_type);
        UPDATE public.posts 
        SET likes = COALESCE(likes, 0) + 1,
            reaction_counts = COALESCE(reaction_counts, '{}'::jsonb) || jsonb_build_object(p_reaction_type, COALESCE((reaction_counts->>p_reaction_type)::int, 0) + 1)
        WHERE id = p_post_id;
    ELSIF v_existing_reaction != p_reaction_type THEN
        UPDATE public.post_reactions SET reaction_type = p_reaction_type WHERE post_id = p_post_id AND user_id = p_user_id;
        UPDATE public.posts 
        SET reaction_counts = COALESCE(reaction_counts, '{}'::jsonb) || jsonb_build_object(
                v_existing_reaction, GREATEST(0, COALESCE((reaction_counts->>v_existing_reaction)::int, 0) - 1),
                p_reaction_type, COALESCE((reaction_counts->>p_reaction_type)::int, 0) + 1
            )
        WHERE id = p_post_id;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION remove_post_reaction(p_post_id BIGINT, p_user_id UUID)
RETURNS void AS $$
DECLARE
    v_existing_reaction TEXT;
BEGIN
    SELECT reaction_type INTO v_existing_reaction FROM public.post_reactions WHERE post_id = p_post_id AND user_id = p_user_id;
    
    IF v_existing_reaction IS NOT NULL THEN
        DELETE FROM public.post_reactions WHERE post_id = p_post_id AND user_id = p_user_id;
        UPDATE public.posts 
        SET likes = GREATEST(0, COALESCE(likes, 0) - 1),
            reaction_counts = COALESCE(reaction_counts, '{}'::jsonb) || jsonb_build_object(v_existing_reaction, GREATEST(0, COALESCE((reaction_counts->>v_existing_reaction)::int, 0) - 1))
        WHERE id = p_post_id;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Enable Realtime for post_reactions
ALTER PUBLICATION supabase_realtime ADD TABLE public.post_reactions;
